force-app/main/default/objects/Apod__c/Apod__c.object-meta.xml
<CustomObject>
    <description>Astronomy Picture of the Day.</description>
    <label>Apod</label>
    <nameField>
        <label>Apod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Apod__c/fields/ApodID__c.field-meta.xml
<CustomField>
    <fullName>ApodID__c</fullName>
    <label>ApodID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apod__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date of the APOD image to retrieve</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ApodServiceTest.cls
/**
 * Test class for ApodService
 * 
 * @see ApodService
 */
@isTest
public with sharing class ApodServiceTest {
    
    @TestSetup
    static void makeData(){
        // create 2 Apod__c records
        List<Apod__c> apods = new List<Apod__c>();
        apods.add(new Apod__c(Name='apod1', ApodID__c = 'apod1', Date__c = Date.today()));
        apods.add(new Apod__c(Name='apod2', ApodID__c = 'apod2', Date__c = Date.today()));
        insert apods;
    }

    @isTest
    static void testCreateApods(){
        // create 2 Apod__c records
        List<Apod__c> apods = new List<Apod__c>();
        apods.add(new Apod__c(Name='apod3', ApodID__c = 'apod3', Date__c = Date.today()));
        apods.add(new Apod__c(Name='apod4', ApodID__c = 'apod4', Date__c = Date.today()));
        ApodService.createApods(apods);
        System.assertEquals(4, [SELECT count() FROM Apod__c]);
    }

    @isTest
    static void testCreateApodsWithDuplicates(){
        // create 2 Apod__c records
        List<Apod__c> apods = new List<Apod__c>();
        apods.add(new Apod__c(Name='apod1', ApodID__c = 'apod1', Date__c = Date.today()));
        apods.add(new Apod__c(Name='apod3', ApodID__c = 'apod3', Date__c = Date.today()));
        ApodService.createApods(apods);
        System.assertEquals(3, [SELECT count() FROM Apod__c]);
    }

    @isTest
    static void testDeleteApods(){
        List<Apod__c> apods = [SELECT Id FROM Apod__c];
        ApodService.deleteApods(apods);
        System.assertEquals(0, [SELECT count() FROM Apod__c]);
    }
}